PUT http://localhost:8081/api/users/current HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NzA4NDQ3OTAsImV4cCI6MTY3MDkwOTU5MCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfTUFOQUdFUiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6Im90cm9jMkBvY2xvY2suaW8ifQ.oJpstdpBdEVxzkAOL_ehyhyWeEmnUJlQwyTyGFVEZO8itDO335CaNGIvWYmnTte0qq7lhLpCleuRbsANiz4zNFEEvwRrQWsIPOWZaJIkRJbk1mSUwTUd9WO_icsd9e3u90P62RFFA_SIRN-4avi258-StlZ2x_LBwvpaAAGrrq6399U-K1fvW_wO0Gmxyc1_phZgiHl1rU4CaKkbhoaQLfOUljerhaCh1cG7UTCjwxWA73qZT9WLLbyspLLTlgBM5FVvejbloR4igUdD8SVS61ZA1JUrUu-8EEb6miBNuVVADcdGeBB9Ihx6Q7lMUqIV83ks8Ppvg3l3oVoevGzV_w

{
    "alias": "Michel"
}