GET http://localhost:8081/api/users/current/offers
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NzA5NTQzOTcsImV4cCI6MTY3MTAxOTE5Nywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfTUFOQUdFUiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6Im90cm9jMkBvY2xvY2suaW8ifQ.a4iz4nj9N9ygdLjFO_MR1v7khy_vWlF8FPx-v5yjb7bRTBUZGLxHFF-rhr4kJVmxnRFP23B0hY-VuSlevAMs4IG1I4139BCy2Lt16N_402YX723U8wKpcQyw61aWUNbVd8Q4DBl8qmvomH9-wvixUzGbj8XUiOkzOlPLHpFVb4M-y2Rqz9q6pAsp1bOPMRtXcwZhR44Ea5-pfzd6uWFCqIuzlY7rrusKno8PCCi4ZYlt_aceWEM3wyXRGvVA5BYYpmaoOCEKuqauoTvmCxt15uZSqvYf8MqumyM4h0IqutbyBkkWSzJ-rlGpnqln60lZOMa6_q733Ktsu6rQ_mtPNQ