GET http://localhost:8081/api/users/current/offers
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NzA0OTU2MDYsImV4cCI6MTY3MDU2MDQwNiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfTUFOQUdFUiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6Im90cm9jMUBvY2xvY2suaW8ifQ.epDqTeL_DLMmwSXWafGLEmpqc-9vaF2o7Ltv8UC5CfgA7UIGqvH3NIZcjTrctqstIn_EIW8x8y1fwyobzO-phxeD5a_32BYEgylW8DJHhf436gyfKCy_PGXSh3lI_77Vgn7gp9QTwfBMcIYZFIU4DqECx-9H3KhYXLtESWvDKXnHKW4uLR44pueS106aGzvB0Ul7aDZf0w1qHkUJ90XgpVoLtooAVJDLxHGefCrZmINm8BpmTVfg_5omQAP78axYFNOFpAukm4H9J87ZHEjdFOaUstOhksrGd_EKKzIPUDXkVRrPjFI-VwdvX_Q4OoYY3XmNOn22pm-GHPNz4XeUAQ