GET http://localhost:8081/api/users/current/offers
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NzA4NTIzMjcsImV4cCI6MTY3MDkxNzEyNywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfTUFOQUdFUiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6Im90cm9jMkBvY2xvY2suaW8ifQ.S9BMucB8bRRfJzBIfCHYmvSjqahxMxFMN23Fs-Txt2zwwy6j-g9LikgPTGqhR2wGBRLaHzo1PYD-k91su2ojTj2QXEpP1ORkTJtR4-K8EmY4rLTCDWrmC89A4iwF4swtvpo2nT4yeJpkG6LWw1WnGky47RGAZ82QCBhgy8fDGS7V-QzGJEx3fo3ODmJPa3mG9Rsf2YTIwFRKBIOYuCV4y5spwwtRPyI9SzKI8mPnzil6Dme93rpuNa6a06cD14-m103_pO0zWBvzlwOkt1INogUiq708eUGAK1lSd9USJfXxz_IUdMKalZjRq4aKFQ2BEAFDBgH9qUBxv_PrEa0UMQ